import { PrismaClient } from '@prisma/client';
import { hash } from 'bcrypt';

const prisma = new PrismaClient();

async function main() {
  console.log('🌱 Rozpoczynam seedowanie bazy danych...');

  // Clear existing quiz data to prevent conflicts
  await prisma.answer.deleteMany({});
  await prisma.question.deleteMany({});
  await prisma.quizSession.deleteMany({});
  await prisma.quiz.deleteMany({});
  await prisma.room.deleteMany({});
  await prisma.style.deleteMany({});
  await prisma.detail.deleteMany({});

  console.log('🗑️ Wyczyszczono poprzednie dane quizu.');

  const hashedPassword = await hash('12345678', 12);

  // Seed users and other non-quiz data if needed
  await prisma.user.upsert({
    where: { email: 'admin@artscore.pro' },
    update: {},
    create: {
      email: 'admin@artscore.pro',
      name: 'Administrator Systemu',
      password: hashedPassword,
      accountType: 'ADMIN',
      isVerified: true,
    },
  });
  console.log('✅ Użytkownik admin gotowy.');

  // 1. Seed Rooms
  const roomsList = ["Salon", "Sypialnia", "Kuchnia", "Jadalnia", "Łazienka", "Przedpokój / Hol", "Gabinet / Biuro domowe", "Pokój dziecięcy", "Pokój młodzieżowy", "Garderoba", "Pokój gościnny", "Pokój hobby / Pracownia", "Spiżarnia", "Pralnia", "Taras / Balkon / Loggia", "Ogród zimowy", "Pokój fitness / Siłownia domowa", "Pokój multimedialny / Kino domowe", "Pokój rekreacyjny / Sala zabaw", "Pokój dla seniora", "Pokój dla niemowlęcia", "Kącik dla zwierząt (np. dla psa/kota)", "Garaż", "Pomieszczenie gospodarcze", "Piwnica", "Stryszek / Strych"];
  await prisma.room.createMany({
    data: roomsList.map(name => ({ name })),
    skipDuplicates: true,
  });
  console.log(`✅ Dodano ${roomsList.length} pomieszczeń.`);

  // 2. Seed Functional Quiz
  const functionalQuiz = await prisma.quiz.create({
    data: {
      title: 'Quiz Funkcjonalny',
      description: 'Zdefiniuj swoje potrzeby funkcjonalne, abyśmy mogli dopasować idealne rozwiązania do Twojego wnętrza.',
      type: 'FUNCTIONAL',
    },
  });
  console.log(`✅ Utworzono "${functionalQuiz.title}".`);

  const functionalQuestions = [
    // === 2.1. Styl życia i nawyki użytkownika ===
    {
      questionCode: 'LIFESTYLE_1',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Ile osób mieszka w twoim domu?',
      type: 'single-choice',
      options: { choices: [{ value: '1', label: '1 osoba' }, { value: '2', label: '2 osoby' }, { value: '3-4', label: '3-4 osoby' }, { value: '5+', label: '5 i więcej' }] },
      branchingLogic: { rules: [{ condition: { value: '1', operator: 'neq' }, action: 'JUMP', target: 'LIFESTYLE_1_FOLLOWUP' }] },
      relevantRooms: ["Salon", "Kuchnia", "Jadalnia", "Łazienka", "Przedpokój / Hol", "Gabinet / Biuro domowe", "Pokój dziecięcy", "Pokój młodzieżowy", "Pokój dla seniora", "Pokój dla niemowlęcia", "Pokój rekreacyjny / Sala zabaw", "Pokój gościnny", "Pomieszczenie gospodarcze"],
      tags: ['demographics'],
    },
    {
      questionCode: 'LIFESTYLE_1_FOLLOWUP',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Kto to mniej więcej? (np. partner, dzieci, dziadkowie)',
      type: 'text',
      options: { placeholder: 'Partner, dzieci, współlokatorzy...' },
      relevantRooms: [],
      tags: ['demographics', 'follow-up'],
    },
    {
        questionCode: 'LIFESTYLE_2',
        category: 'Styl życia i nawyki użytkownika',
        text: 'W jakim wieku są osoby w domu?',
        type: 'multiple-choice',
        options: { choices: [{ value: '0-2', label: 'Niemowlęta (0-2 lata)' }, { value: '3-10', label: 'Małe dzieci (3-10 lat)' }, { value: '11-17', label: 'Nastolatki (11-17 lat)' }, { value: '18-64', label: 'Dorośli (18-64 lata)' }, { value: '65+', label: 'Seniorzy (65+)' }] },
        branchingLogic: { rules: [{ condition: { value: '0-2', operator: 'contains' }, action: 'JUMP', target: 'LIFESTYLE_2_FOLLOWUP' }] },
        relevantRooms: ["Pokój dziecięcy", "Pokój młodzieżowy", "Pokój dla seniora", "Pokój dla niemowlęcia", "Pokój rekreacyjny / Sala zabaw", "Salon", "Kuchnia", "Łazienka", "Przedpokój / Hol"],
        tags: ['demographics'],
    },
    {
        questionCode: 'LIFESTYLE_2_FOLLOWUP',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Proszę, podaj liczbę osób w każdej wybranej grupie wiekowej.',
        type: 'text',
        options: { placeholder: 'np. Dorośli: 2, Dzieci: 1' },
        relevantRooms: [],
        tags: ['demographics', 'follow-up'],
    },
    {
        questionCode: 'LIFESTYLE_3',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Czy ktoś w domu ma ograniczenia ruchowe lub specjalne potrzeby?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }, { value: 'n/a', label: 'Nie wiem/nie dotyczy' }] },
        branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'LIFESTYLE_3_FOLLOWUP' }] },
        relevantRooms: ["Łazienka", "Pokój dla seniora", "Pokój dziecięcy", "Pokój dla niemowlęcia", "Przedpokój / Hol", "Kuchnia", "Salon", "Pomieszczenie gospodarcze"],
        tags: ['accessibility'],
    },
    {
        questionCode: 'LIFESTYLE_3_FOLLOWUP',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Dla ilu osób i w jakich pomieszczeniach należy uwzględnić specjalne potrzeby?',
        type: 'text',
        options: { placeholder: 'np. brak progów w łazience lub przedpokoju' },
        relevantRooms: [],
        tags: ['accessibility', 'follow-up'],
    },
    {
        questionCode: 'LIFESTYLE_4',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Czyje potrzeby chcesz uwzględnić w rekomendacjach?',
        type: 'single-choice',
        options: { choices: [{ value: 'all', label: 'Wszystkich domowników' }, { value: 'selected', label: 'Wybranych osób' }, { value: 'mine', label: 'Tylko moje' }] },
        relevantRooms: ["Salon", "Kuchnia", "Jadalnia", "Sypialnia", "Gabinet / Biuro domowe", "Pokój młodzieżowy", "Pokój dla seniora", "Łazienka"],
        tags: ['decision-making'],
    },
    {
      questionCode: 'LIFESTYLE_5_A',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Jak często jecie razem posiłki?',
      type: 'single-choice',
      options: { choices: [{ value: 'daily', label: 'Codziennie' }, { value: 'weekly', label: 'Kilka razy w tygodniu' }, { value: 'rarely', label: 'Rzadko' }] },
      relevantRooms: ["Kuchnia", "Jadalnia"],
      tags: ['habits', 'family'],
    },
    {
      questionCode: 'LIFESTYLE_5_B',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Ile godzin tygodniowo spędzacie razem na relaksie w jednym pomieszczeniu?',
      type: 'single-choice',
      options: { choices: [{ value: 'low', label: '0-5h' }, { value: 'medium', label: '5-15h' }, { value: 'high', label: '>15h' }] },
      relevantRooms: ["Salon", "Pokój multimedialny / Kino domowe"],
      tags: ['habits', 'family', 'relaxation'],
    },
    {
      questionCode: 'LIFESTYLE_5_C',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Czy macie wspólne hobby w domu, jak gry czy filmy?',
      type: 'single-choice',
      options: { choices: [{ value: 'often', label: 'Tak, często' }, { value: 'sometimes', label: 'Czasem' }, { value: 'no', label: 'Nie' }] },
      relevantRooms: ["Pokój rekreacyjny / Sala zabaw", "Pokój hobby / Pracownia"],
      tags: ['habits', 'hobby'],
    },
    {
      questionCode: 'LIFESTYLE_5_D',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Jak często dochodzi do konfliktów o wspólną przestrzeń?',
      type: 'single-choice',
      options: { choices: [{ value: 'rarely', label: 'Rzadko' }, { value: 'moderately', label: 'Umiarkowanie' }, { value: 'often', label: 'Często' }] },
      branchingLogic: { rules: [{ condition: { value: 'often', operator: 'eq' }, action: 'JUMP', target: 'LIFESTYLE_5_D_FOLLOWUP' }] },
      relevantRooms: ["Gabinet / Biuro domowe", "Salon", "Łazienka"],
      tags: ['habits', 'conflicts'],
    },
    {
      questionCode: 'LIFESTYLE_5_D_FOLLOWUP',
      category: 'Styl życia i nawyki użytkownika',
      text: 'W jakich sytuacjach najczęściej dochodzi do konfliktów i jak sobie z nimi radzicie?',
      type: 'text',
      options: { placeholder: 'np. osobne strefy w salonie' },
      relevantRooms: [],
      tags: ['habits', 'conflicts', 'follow-up'],
    },
    {
      questionCode: 'LIFESTYLE_6',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Jak bardzo chcesz, by przestrzeń była elastyczna i dopasowana do różnych potrzeb?',
      type: 'slider',
      options: { min: 1, max: 5, referencePoints: [{ value: 1, label: 'Stała' }, { value: 3, label: 'Umiarkowanie elastyczna' }, { value: 5, label: 'Bardzo elastyczna' }] },
      branchingLogic: { rules: [{ condition: { value: 3, operator: 'gt' }, action: 'JUMP', target: 'LIFESTYLE_6_FOLLOWUP' }] },
      relevantRooms: ["Salon", "Kuchnia", "Jadalnia", "Sypialnia", "Łazienka", "Pokój młodzieżowy", "Pokój dla seniora", "Przedpokój / Hol"],
      tags: ['flexibility'],
    },
    {
      questionCode: 'LIFESTYLE_6_FOLLOWUP',
      category: 'Styl życia i nawyki użytkownika',
      text: 'W jakich aspektach elastyczność jest najważniejsza?',
      type: 'text',
      options: { placeholder: 'np. prywatność dla nastolatków, miejsce do pracy' },
      relevantRooms: [],
      tags: ['flexibility', 'follow-up'],
    },
    {
      questionCode: 'LIFESTYLE_7',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Ile godzin dziennie średnio spędzacie w tym pomieszczeniu?',
      type: 'slider',
      options: { min: 0, max: 8, step: 1, referencePoints: [{ value: 0, label: '0-2h' }, { value: 4, label: '2-4h' }, { value: 6, label: '4-6h' }, { value: 8, label: '>6h' }] },
      branchingLogic: { rules: [{ condition: { value: 4, operator: 'gt' }, action: 'JUMP', target: 'LIFESTYLE_7_FOLLOWUP' }] },
      relevantRooms: ["Salon", "Pokój multimedialny / Kino domowe", "Pokój rekreacyjny / Sala zabaw", "Jadalnia", "Kuchnia"],
      tags: ['usage'],
    },
    {
      questionCode: 'LIFESTYLE_7_FOLLOWUP',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Na jakich aktywnościach głównie spędzacie ten czas?',
      type: 'text',
      options: { placeholder: 'np. oglądanie TV, gotowanie, zabawa z dziećmi' },
      relevantRooms: [],
      tags: ['usage', 'follow-up'],
    },
    {
      questionCode: 'LIFESTYLE_8',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Czy ty lub ktoś z domowników pracuje lub uczy się zdalnie?',
      type: 'single-choice',
      options: { choices: [{ value: 'none', label: 'Nikt' }, { value: 'one', label: 'Jedna osoba' }, { value: 'some', label: 'Kilka osób' }, { value: 'all', label: 'Wszyscy' }] },
      branchingLogic: { rules: [{ condition: { value: 'none', operator: 'neq' }, action: 'JUMP', target: 'LIFESTYLE_8_FOLLOWUP' }] },
      relevantRooms: ["Gabinet / Biuro domowe", "Salon", "Pokój młodzieżowy", "Kuchnia", "Sypialnia"],
      tags: ['remote-work'],
    },
    {
      questionCode: 'LIFESTYLE_8_FOLLOWUP',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Ile godzin dziennie i dla ilu osób potrzebne jest miejsce do pracy/nauki?',
      type: 'text',
      options: { placeholder: 'np. 8h dla 1 osoby, 4h dla 2 osób' },
      relevantRooms: [],
      tags: ['remote-work', 'follow-up'],
    },
    {
      questionCode: 'LIFESTYLE_9_A',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Czy zdarzają się konflikty o prywatność (np. kolejki do łazienki)?',
      type: 'single-choice',
      options: { choices: [{ value: 'often', label: 'Tak, często' }, { value: 'moderately', label: 'Umiarkowanie' }, { value: 'rarely', label: 'Rzadko' }, { value: 'no', label: 'Nie' }] },
      branchingLogic: { rules: [{ condition: { value: 'rarely', operator: 'neq' }, action: 'JUMP', target: 'LIFESTYLE_9_A_FOLLOWUP' }] },
      relevantRooms: ["Sypialnia", "Gabinet / Biuro domowe", "Pokój młodzieżowy", "Pokój dla seniora", "Łazienka", "Przedpokój / Hol"],
      tags: ['privacy', 'conflicts'],
    },
    {
      questionCode: 'LIFESTYLE_9_A_FOLLOWUP',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Jakie rozwiązania mogłyby pomóc rozwiązać te konflikty?',
      type: 'text',
      options: { placeholder: 'np. przegrody w pokoju, harmonogram w łazience' },
      relevantRooms: [],
      tags: ['privacy', 'conflicts', 'follow-up'],
    },
    {
      questionCode: 'LIFESTYLE_9_B',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Ile godzin dziennie potrzebujecie ciszy w osobnej strefie?',
      type: 'single-choice',
      options: { choices: [{ value: 'low', label: '0-2h' }, { value: 'medium', label: '2-4h' }, { value: 'high', label: '>4h' }] },
      relevantRooms: ["Gabinet / Biuro domowe", "Pokój dla seniora", "Sypialnia"],
      tags: ['privacy', 'quiet-zone'],
    },
    {
        questionCode: 'LIFESTYLE_10',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Czy macie zwierzęta domowe?',
        type: 'single-choice',
        options: { choices: [{ value: 'dogs', label: 'Tak, psy' }, { value: 'cats', label: 'Tak, koty' }, { value: 'other', label: 'Tak, inne' }, { value: 'no', label: 'Nie' }] },
        branchingLogic: { rules: [{ condition: { value: 'no', operator: 'neq' }, action: 'JUMP', target: 'LIFESTYLE_10_FOLLOWUP' }] },
        relevantRooms: ["Kącik dla zwierząt (np. dla psa/kota)", "Salon", "Sypialnia", "Kuchnia", "Łazienka", "Przedpokój / Hol"],
        tags: ['pets'],
    },
    {
        questionCode: 'LIFESTYLE_10_FOLLOWUP',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Ile ich jest i jakie mają potrzeby w codziennym użytkowaniu?',
        type: 'text',
        options: { placeholder: 'np. kącik do spania w salonie, odporne podłogi' },
        relevantRooms: [],
        tags: ['pets', 'follow-up'],
    },
    {
        questionCode: 'LIFESTYLE_11',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Jakiego typu przechowywania potrzebujecie?',
        type: 'multiple-choice',
        options: { choices: [
            { value: 'hidden', label: 'Schowane za drzwiami/szafami' },
            { value: 'open', label: 'Pod ręką na otwartych półkach' },
            { value: 'aesthetic', label: 'Estetyczne z ukrytymi mechanizmami' },
            { value: 'seasonal', label: 'Sezonowe, rotacyjne' },
            { value: 'secure', label: 'Bezpieczne, zamykane' },
            { value: 'multifunctional', label: 'Multifunkcjonalne (zintegrowane z meblami)' }
        ]},
        branchingLogic: { rules: [{ condition: { value: 'hidden', operator: 'contains' }, action: 'JUMP', target: 'LIFESTYLE_11_FOLLOWUP' }] },
        relevantRooms: ["Przedpokój / Hol", "Garderoba", "Spiżarnia", "Garaż", "Pomieszczenie gospodarcze", "Piwnica", "Stryszek / Strych"],
        tags: ['storage'],
    },
    {
        questionCode: 'LIFESTYLE_11_FOLLOWUP',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Opisz dokładniej swoje potrzeby dotyczące przechowywania.',
        type: 'text',
        options: { placeholder: 'np. szybki dostęp do butów w przedpokoju' },
        relevantRooms: [],
        tags: ['storage', 'follow-up'],
    },
    {
        questionCode: 'LIFESTYLE_12',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Czy lubicie otwarte czy wydzielone przestrzenie?',
        type: 'image-choice',
        options: { choices: [
            { value: 'open', label: 'Otwarte', imageUrl: '/images/placeholder.jpg' },
            { value: 'closed', label: 'Wydzielone', imageUrl: '/images/placeholder.jpg' },
            { value: 'mixed', label: 'Mieszane', imageUrl: '/images/placeholder.jpg' }
        ]},
        branchingLogic: { rules: [{ condition: { value: 'open', operator: 'eq' }, action: 'JUMP', target: 'LIFESTYLE_12_FOLLOWUP' }] },
        relevantRooms: ["Salon", "Kuchnia", "Jadalnia", "Przedpokój / Hol", "Łazienka"],
        tags: ['space-planning'],
    },
    {
        questionCode: 'LIFESTYLE_12_FOLLOWUP',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Dlaczego preferujesz ten typ przestrzeni?',
        type: 'text',
        options: { placeholder: 'np. dla gotowania z rodziną w otwartej kuchni' },
        relevantRooms: [],
        tags: ['space-planning', 'follow-up'],
    },
    {
        questionCode: 'LIFESTYLE_13',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Jak ważne jest dla Was miejsce do relaksu?',
        type: 'slider',
        options: { min: 1, max: 5, referencePoints: [{ value: 1, label: 'Nieważne' }, { value: 3, label: 'Umiarkowanie ważne' }, { value: 5, label: 'Bardzo ważne' }] },
        branchingLogic: { rules: [{ condition: { value: 3, operator: 'gt' }, action: 'JUMP', target: 'LIFESTYLE_13_FOLLOWUP' }] },
        relevantRooms: ["Salon", "Sypialnia", "Taras / Balkon / Loggia", "Ogród zimowy", "Pokój rekreacyjny / Sala zabaw"],
        tags: ['relaxation'],
    },
    {
        questionCode: 'LIFESTYLE_13_FOLLOWUP',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Jakie aktywności relaksacyjne i dla ilu osób planujecie?',
        type: 'text',
        options: { placeholder: 'np. czytanie na tarasie dla 2 osób' },
        relevantRooms: [],
        tags: ['relaxation', 'follow-up'],
    },
    {
      questionCode: 'LIFESTYLE_14_A',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Czy macie różne preferencje co do temperatury w pomieszczeniach?',
      type: 'single-choice',
      options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
      branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'LIFESTYLE_14_A_FOLLOWUP' }] },
      relevantRooms: ["Sypialnia", "Pokój dla seniora", "Salon"],
      tags: ['climate', 'preferences'],
    },
    {
      questionCode: 'LIFESTYLE_14_A_FOLLOWUP',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Jakie są to różnice i jak je godzicie?',
      type: 'text',
      options: { placeholder: 'np. jedno lubi chłodniej, drugie cieplej' },
      relevantRooms: [],
      tags: ['climate', 'preferences', 'follow-up'],
    },
    {
      questionCode: 'LIFESTYLE_14_B',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Ile godzin dziennie potrzebujecie stabilnej temperatury w kluczowych przestrzeniach?',
      type: 'single-choice',
      options: { choices: [{ value: 'low', label: '0-4h' }, { value: 'medium', label: '4-8h' }, { value: 'high', label: '>8h' }] },
      relevantRooms: ["Kuchnia", "Gabinet / Biuro domowe"],
      tags: ['climate', 'stability'],
    },
    {
      questionCode: 'LIFESTYLE_15_A',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Czy potrzebujecie dodatkowej izolacji akustycznej w którymś z pomieszczeń?',
      type: 'single-choice',
      options: { choices: [{ value: 'high', label: 'Tak, jest to bardzo ważne' }, { value: 'medium', label: 'Umiarkowanie' }, { value: 'no', label: 'Nie' }] },
      branchingLogic: { rules: [{ condition: { value: 'no', operator: 'neq' }, action: 'JUMP', target: 'LIFESTYLE_15_A_FOLLOWUP' }] },
      relevantRooms: ["Gabinet / Biuro domowe", "Sypialnia", "Pokój multimedialny / Kino domowe"],
      tags: ['acoustics'],
    },
    {
      questionCode: 'LIFESTYLE_15_A_FOLLOWUP',
      category: 'Styl życia i nawyki użytkownika',
      text: 'W jakich sytuacjach izolacja akustyczna jest kluczowa?',
      type: 'text',
      options: { placeholder: 'np. podczas pracy zdalnej, snu dziecka' },
      relevantRooms: [],
      tags: ['acoustics', 'follow-up'],
    },
    {
      questionCode: 'LIFESTYLE_15_B',
      category: 'Styl życia i nawyki użytkownika',
      text: 'Czy hałas z innych części domu (np. zabawa dzieci) jest problemem?',
      type: 'single-choice',
      options: { choices: [{ value: 'often', label: 'Tak, w wielu sytuacjach' }, { value: 'sometimes', label: 'Czasem' }, { value: 'no', label: 'Nie' }] },
      relevantRooms: ["Salon", "Pokój rekreacyjny / Sala zabaw", "Kuchnia", "Gabinet / Biuro domowe"],
      tags: ['acoustics', 'noise'],
    },
    {
        questionCode: 'LIFESTYLE_16',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Czy ktoś z domowników potrzebuje specjalnych rozwiązań (np. antyalergicznych)?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
        branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'LIFESTYLE_16_FOLLOWUP' }] },
        relevantRooms: ["Pokój dla seniora", "Łazienka", "Pokój dziecięcy", "Pokój dla niemowlęcia", "Kuchnia", "Salon", "Sypialnia"],
        tags: ['special-needs'],
    },
    {
        questionCode: 'LIFESTYLE_16_FOLLOWUP',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Jakie to rozwiązania i dla ilu osób?',
        type: 'text',
        options: { placeholder: 'np. antyalergiczne materiały w sypialni' },
        relevantRooms: [],
        tags: ['special-needs', 'follow-up'],
    },
    {
        questionCode: 'LIFESTYLE_17',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Ile godzin tygodniowo korzystacie z przestrzeni zewnętrznych (balkon, taras)?',
        type: 'slider',
        options: { min: 0, max: 15, step: 1, referencePoints: [{ value: 0, label: '0-5h' }, { value: 7, label: '5-10h' }, { value: 15, label: '>10h' }] },
        branchingLogic: { rules: [{ condition: { value: 5, operator: 'gt' }, action: 'JUMP', target: 'LIFESTYLE_17_FOLLOWUP' }] },
        relevantRooms: ["Taras / Balkon / Loggia", "Ogród zimowy", "Salon"],
        tags: ['outdoor-living'],
    },
    {
        questionCode: 'LIFESTYLE_17_FOLLOWUP',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Do jakich aktywności wykorzystujecie tę przestrzeń?',
        type: 'text',
        options: { placeholder: 'np. grill, relaks, uprawa roślin' },
        relevantRooms: [],
        tags: ['outdoor-living', 'follow-up'],
    },
    {
        questionCode: 'LIFESTYLE_18',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Gdzie wolicie spędzać wolny czas - w domu czy poza nim?',
        type: 'single-choice',
        options: { choices: [{ value: 'home', label: 'Głównie w domu' }, { value: 'mixed', label: 'Pół na pół' }, { value: 'outside', label: 'Głównie poza domem' }] },
        branchingLogic: { rules: [{ condition: { value: 'home', operator: 'eq' }, action: 'JUMP', target: 'LIFESTYLE_18_FOLLOWUP' }] },
        relevantRooms: ["Pokój fitness / Siłownia domowa", "Pokój hobby / Pracownia", "Pokój rekreacyjny / Sala zabaw", "Salon"],
        tags: ['leisure'],
    },
    {
        questionCode: 'LIFESTYLE_18_FOLLOWUP',
        category: 'Styl życia i nawyki użytkownika',
        text: 'Jakie aktywności domowe preferujecie i dla ilu osób?',
        type: 'text',
        options: { placeholder: 'np. ćwiczenia w domowej siłowni, majsterkowanie' },
        relevantRooms: [],
        tags: ['leisure', 'follow-up'],
    },
    // === 2.2. Funkcjonalność i wyposażenie wnętrz ===
    {
        questionCode: 'FUNCTIONALITY_1',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Jak wiele rzeczy (ubrań, narzędzi, zapasów) zazwyczaj przechowujecie?',
        type: 'slider',
        options: { min: 1, max: 5, referencePoints: [{ value: 1, label: 'Mało' }, { value: 3, label: 'Średnio' }, { value: 5, label: 'Dużo' }] },
        branchingLogic: { rules: [{ condition: { value: 3, operator: 'gt' }, action: 'JUMP', target: 'FUNCTIONALITY_1_FOLLOWUP' }] },
        relevantRooms: ["Garderoba", "Spiżarnia", "Garaż", "Piwnica", "Stryszek / Strych", "Pomieszczenie gospodarcze", "Przedpokój / Hol"],
        tags: ['storage'],
    },
    {
        questionCode: 'FUNCTIONALITY_1_FOLLOWUP',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Czy przechowujecie dużo rzeczy sezonowych?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
        relevantRooms: [],
        tags: ['storage', 'follow-up'],
    },
    {
        questionCode: 'FUNCTIONALITY_2',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Jak radzicie sobie z zabawkami w różnych częściach domu?',
        type: 'single-choice',
        options: { choices: [
            { value: 'organized', label: 'Mamy dedykowane miejsca i kosze' },
            { value: 'chaotic', label: 'Są wszędzie, to ciągły problem' },
            { value: 'none', label: 'Nie dotyczy (brak dzieci)' }
        ]},
        branchingLogic: { rules: [{ condition: { value: 'chaotic', operator: 'eq' }, action: 'JUMP', target: 'FUNCTIONALITY_2_FOLLOWUP' }] },
        relevantRooms: ["Pokój dziecięcy", "Pokój dla niemowlęcia", "Pokój rekreacyjny / Sala zabaw", "Salon", "Kuchnia", "Łazienka", "Przedpokój / Hol"],
        tags: ['storage', 'children'],
    },
    {
        questionCode: 'FUNCTIONALITY_2_FOLLOWUP',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Jak często problem rozrzuconych zabawek jest uciążliwy?',
        type: 'single-choice',
        options: { choices: [{ value: 'daily', label: 'Codziennie' }, { value: 'weekly', label: 'Kilka razy w tygodniu' }, { value: 'rarely', label: 'Rzadko' }] },
        relevantRooms: [],
        tags: ['storage', 'children', 'follow-up'],
    },
    {
        questionCode: 'FUNCTIONALITY_3',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Jak obecność zwierząt wpływa na meble i wyposażenie?',
        type: 'single-choice',
        options: { choices: [
            { value: 'damage', label: 'Powodują zniszczenia (drapanie, gryzienie)' },
            { value: 'dirt', label: 'Głównie brudzą (sierść, łapy)' },
            { value: 'none', label: 'Nie dotyczy (brak zwierząt)' }
        ]},
        branchingLogic: { rules: [{ condition: { value: 'none', operator: 'neq' }, action: 'JUMP', target: 'FUNCTIONALITY_3_FOLLOWUP' }] },
        relevantRooms: ["Kącik dla zwierząt (np. dla psa/kota)", "Salon", "Sypialnia", "Kuchnia", "Łazienka"],
        tags: ['pets', 'furniture'],
    },
    {
        questionCode: 'FUNCTIONALITY_3_FOLLOWUP',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Jakie rozwiązania w związku z tym byłyby najbardziej pomocne?',
        type: 'text',
        options: { placeholder: 'np. odporne na drapanie materiały, łatwe w czyszczeniu podłogi' },
        relevantRooms: [],
        tags: ['pets', 'furniture', 'follow-up'],
    },
    {
        questionCode: 'FUNCTIONALITY_4',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Czy lubicie często zmieniać układ mebli?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }, { value: 'maybe', label: 'Nie wiem' }] },
        branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'FUNCTIONALITY_4_FOLLOWUP' }] },
        relevantRooms: ["Salon", "Sypialnia", "Jadalnia", "Kuchnia"],
        tags: ['furniture', 'flexibility'],
    },
    {
        questionCode: 'FUNCTIONALITY_4_FOLLOWUP',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Jak często i dlaczego zmieniacie układ mebli?',
        type: 'text',
        options: { placeholder: 'np. co kilka miesięcy dla odświeżenia' },
        relevantRooms: [],
        tags: ['furniture', 'flexibility', 'follow-up'],
    },
    {
        questionCode: 'FUNCTIONALITY_5',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Co jest ważniejsze: wygoda mebli (nawet kosztem ceny) czy ich podstawowa funkcjonalność (jeśli używane sporadycznie)?',
        type: 'single-choice',
        options: { choices: [
            { value: 'comfort', label: 'Super wygodne, nawet jeśli droższe' },
            { value: 'basic', label: 'Podstawowe, jeśli używam sporadycznie' },
            { value: 'depends', label: 'Zależy od pomieszczenia' }
        ]},
        branchingLogic: { rules: [{ condition: { value: 'depends', operator: 'eq' }, action: 'JUMP', target: 'FUNCTIONALITY_5_FOLLOWUP' }] },
        relevantRooms: ["Sypialnia", "Gabinet / Biuro domowe", "Salon", "Kuchnia"],
        tags: ['furniture', 'comfort', 'trade-off'],
    },
    {
        questionCode: 'FUNCTIONALITY_5_FOLLOWUP',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'W których pomieszczeniach wygoda jest priorytetem, a w których wystarczy podstawowa funkcjonalność?',
        type: 'text',
        options: { placeholder: 'np. Wygoda w salonie, podstawowe w pokoju gościnnym' },
        relevantRooms: [],
        tags: ['furniture', 'comfort', 'trade-off', 'follow-up'],
    },
    {
        questionCode: 'FUNCTIONALITY_6',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Wolisz łatwe sprzątanie (nawet kosztem szybszego zużycia materiałów) czy trwałość (nawet jeśli trudniejsze w czyszczeniu)?',
        type: 'trade-off',
        options: {
            optionA: { value: 'easy_clean', label: 'Łatwe sprzątanie', description: 'Materiały mogą zużywać się szybciej.' },
            optionB: { value: 'durable', label: 'Trwałość', description: 'Materiały mogą być trudniejsze w czyszczeniu.' }
        },
        relevantRooms: ["Kuchnia", "Łazienka", "Pralnia", "Salon", "Pokój dziecięcy"],
        tags: ['maintenance', 'materials', 'trade-off'],
    },
    {
        questionCode: 'FUNCTIONALITY_7',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Preferujesz proste, minimalistyczne meble (łatwiejsze w utrzymaniu) czy bardziej ozdobne (więcej detali, trudniejsze czyszczenie)?',
        type: 'image-choice',
        options: { choices: [
            { value: 'simple', label: 'Proste', imageUrl: '/images/placeholder.jpg' },
            { value: 'ornate', label: 'Ozdobne', imageUrl: '/images/placeholder.jpg' },
            { value: 'mixed', label: 'Mieszane', imageUrl: '/images/placeholder.jpg' }
        ]},
        relevantRooms: ["Salon", "Jadalnia", "Sypialnia", "Kuchnia"],
        tags: ['furniture', 'style', 'maintenance'],
    },
    {
        questionCode: 'FUNCTIONALITY_8',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Czy macie dużo ubrań i butów?',
        type: 'slider',
        options: { min: 1, max: 5, referencePoints: [{ value: 1, label: 'Mało' }, { value: 3, label: 'Średnio' }, { value: 5, label: 'Dużo' }] },
        branchingLogic: { rules: [{ condition: { value: 3, operator: 'gt' }, action: 'JUMP', target: 'FUNCTIONALITY_8_FOLLOWUP' }] },
        relevantRooms: ["Garderoba", "Sypialnia", "Przedpokój / Hol", "Piwnica"],
        tags: ['storage', 'clothing'],
    },
    {
        questionCode: 'FUNCTIONALITY_8_FOLLOWUP',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Czy potrzebujecie specjalnych rozwiązań na odzież i obuwie sezonowe?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
        relevantRooms: [],
        tags: ['storage', 'clothing', 'follow-up'],
    },
    {
        questionCode: 'FUNCTIONALITY_9',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Czy macie dużo sprzętu sezonowego (sportowy, ogrodowy)?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
        branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'FUNCTIONALITY_9_FOLLOWUP' }] },
        relevantRooms: ["Piwnica", "Stryszek / Strych", "Pokój fitness / Siłownia domowa", "Garaż", "Pomieszczenie gospodarcze", "Taras / Balkon / Loggia"],
        tags: ['storage', 'seasonal'],
    },
    {
        questionCode: 'FUNCTIONALITY_9_FOLLOWUP',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Jaki to sprzęt i gdzie go przechowujecie poza sezonem?',
        type: 'text',
        options: { placeholder: 'np. narty w garażu, meble ogrodowe w piwnicy' },
        relevantRooms: [],
        tags: ['storage', 'seasonal', 'follow-up'],
    },
    {
      questionCode: 'FUNCTIONALITY_10',
      category: 'Funkcjonalność i wyposażenie wnętrz',
      text: 'Czy potrzebujecie dedykowanego miejsca na sprzęt do sprzątania (odkurzacz, mop, środki czystości)?',
      type: 'single-choice',
      options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
      branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'FUNCTIONALITY_10_FOLLOWUP' }] },
      relevantRooms: ["Pralnia", "Pomieszczenie gospodarcze", "Kuchnia", "Łazienka"],
      tags: ['storage', 'cleaning-supplies'],
    },
    {
      questionCode: 'FUNCTIONALITY_10_FOLLOWUP',
      category: 'Funkcjonalność i wyposażenie wnętrz',
      text: 'Jak dużo sprzętu i środków czystości przechowujecie?',
      type: 'text',
      options: { placeholder: 'np. odkurzacz, mop, 5-10 środków czystości' },
      relevantRooms: [],
      tags: ['storage', 'cleaning-supplies', 'follow-up'],
    },
    {
      questionCode: 'FUNCTIONALITY_11',
      category: 'Funkcjonalność i wyposażenie wnętrz',
      text: 'Czy macie dużo dokumentów, książek lub pamiątek do przechowania?',
      type: 'single-choice',
      options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
      branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'FUNCTIONALITY_11_FOLLOWUP' }] },
      relevantRooms: ["Gabinet / Biuro domowe", "Salon", "Piwnica", "Stryszek / Strych"],
      tags: ['storage', 'personal-items'],
    },
    {
      questionCode: 'FUNCTIONALITY_11_FOLLOWUP',
      category: 'Funkcjonalność i wyposażenie wnętrz',
      text: 'Jakiego typu przechowywania na te rzeczy potrzebujecie (np. zamykane, bezpieczne)?',
      type: 'text',
      options: { placeholder: 'np. zamykane szuflady na dokumenty' },
      relevantRooms: [],
      tags: ['storage', 'personal-items', 'follow-up'],
    },
    {
      questionCode: 'FUNCTIONALITY_12',
      category: 'Funkcjonalność i wyposażenie wnętrz',
      text: 'Czy lubicie wbudowane oświetlenie w meblach (np. w szafach, witrynach)?',
      type: 'single-choice',
      options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
      branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'FUNCTIONALITY_12_FOLLOWUP' }] },
      relevantRooms: ["Kuchnia", "Sypialnia", "Garderoba", "Łazienka", "Salon"],
      tags: ['lighting', 'furniture'],
    },
    {
      questionCode: 'FUNCTIONALITY_12_FOLLOWUP',
      category: 'Funkcjonalność i wyposażenie wnętrz',
      text: 'W jakich miejscach i do czego takie oświetlenie byłoby najbardziej przydatne?',
      type: 'text',
      options: { placeholder: 'np. oświetlenie blatu w kuchni, podświetlenie półek w garderobie' },
      relevantRooms: [],
      tags: ['lighting', 'furniture', 'follow-up'],
    },
    {
      questionCode: 'FUNCTIONALITY_13',
      category: 'Funkcjonalność i wyposażenie wnętrz',
      text: 'Czy cenicie sobie ukryte schowki i sprytne rozwiązania do przechowywania?',
      type: 'single-choice',
      options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
      branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'FUNCTIONALITY_13_FOLLOWUP' }] },
      relevantRooms: ["Kuchnia", "Garderoba", "Salon", "Pokój dziecięcy", "Sypialnia"],
      tags: ['storage', 'smart-solutions'],
    },
    {
      questionCode: 'FUNCTIONALITY_13_FOLLOWUP',
      category: 'Funkcjonalność i wyposażenie wnętrz',
      text: 'Do przechowywania jakich rzeczy przydałyby się ukryte schowki?',
      type: 'text',
      options: { placeholder: 'np. na przyprawy w kuchni, na kable w salonie' },
      relevantRooms: [],
      tags: ['storage', 'smart-solutions', 'follow-up'],
    },
    {
        questionCode: 'FUNCTIONALITY_14',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Jak często i ilu gości przyjmujecie?',
        type: 'single-choice',
        options: { choices: [
            { value: 'often', label: 'Często (co tydzień, >4 osoby)' },
            { value: 'sometimes', label: 'Sporadycznie (co miesiąc, 1-3 osoby)' },
            { value: 'rarely', label: 'Rzadko (<1x/miesiąc)' }
        ]},
        branchingLogic: { rules: [{ condition: { value: 'rarely', operator: 'neq' }, action: 'JUMP', target: 'FUNCTIONALITY_14_FOLLOWUP' }] },
        relevantRooms: ["Pokój gościnny", "Salon", "Jadalnia", "Kuchnia"],
        tags: ['hospitality'],
    },
    {
        questionCode: 'FUNCTIONALITY_14_FOLLOWUP',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Jakie specjalne potrzeby mają Wasi goście?',
        type: 'text',
        options: { placeholder: 'np. dodatkowe miejsce do spania, rozkładany stół' },
        relevantRooms: [],
        tags: ['hospitality', 'follow-up'],
    },
    {
        questionCode: 'FUNCTIONALITY_15',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Co jest ważniejsze: trwałe meble na lata (nawet droższe) czy tańsze, które można częściej wymieniać?',
        type: 'trade-off',
        options: {
            optionA: { value: 'durable', label: 'Trwałe na lata', description: 'Wyższa inwestycja początkowa.' },
            optionB: { value: 'disposable', label: 'Tańsze na krócej', description: 'Łatwiejsza wymiana, np. przy dzieciach.' }
        },
        relevantRooms: ["Kuchnia", "Pokój dziecięcy", "Salon", "Sypialnia"],
        tags: ['furniture', 'durability', 'trade-off'],
    },
    {
        questionCode: 'FUNCTIONALITY_16',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Wolisz materiały naturalne (wymagające więcej pielęgnacji) czy syntetyczne (łatwiejsze w utrzymaniu)?',
        type: 'image-choice',
        options: { choices: [
            { value: 'natural', label: 'Naturalne', imageUrl: '/images/placeholder.jpg' },
            { value: 'synthetic', label: 'Łatwe w utrzymaniu', imageUrl: '/images/placeholder.jpg' },
            { value: 'mixed', label: 'Mieszane', imageUrl: '/images/placeholder.jpg' }
        ]},
        relevantRooms: ["Kuchnia", "Łazienka", "Salon", "Jadalnia"],
        tags: ['materials', 'maintenance'],
    },
    {
        questionCode: 'FUNCTIONALITY_17',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Czy macie lub planujecie mieć rośliny doniczkowe?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
        branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'FUNCTIONALITY_17_FOLLOWUP' }] },
        relevantRooms: ["Ogród zimowy", "Taras / Balkon / Loggia", "Salon", "Sypialnia", "Kuchnia", "Jadalnia"],
        tags: ['plants'],
    },
    {
        questionCode: 'FUNCTIONALITY_17_FOLLOWUP',
        category: 'Funkcjonalność i wyposażenie wnętrz',
        text: 'Jak dużo roślin posiadacie i czy mają specjalne wymagania?',
        type: 'text',
        options: { placeholder: 'np. >30 sztuk, potrzebują dużo światła' },
        relevantRooms: [],
        tags: ['plants', 'follow-up'],
    },
    {
      questionCode: 'FUNCTIONALITY_18',
      category: 'Funkcjonalność i wyposażenie wnętrz',
      text: 'Czy potrzebujecie dużo miejsca do przechowywania kosmetyków lub środków czystości?',
      type: 'single-choice',
      options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
      branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'FUNCTIONALITY_18_FOLLOWUP' }] },
      relevantRooms: ["Łazienka", "Pralnia", "Kuchnia", "Pomieszczenie gospodarcze"],
      tags: ['storage', 'bathroom-supplies'],
    },
    {
      questionCode: 'FUNCTIONALITY_18_FOLLOWUP',
      category: 'Funkcjonalność i wyposażenie wnętrz',
      text: 'Ile mniej więcej sztuk (butelek, opakowań) przechowujecie?',
      type: 'single-choice',
      options: { choices: [{ value: 'low', label: '< 20' }, { value: 'medium', label: '20-50' }, { value: 'high', label: '> 50' }] },
      relevantRooms: [],
      tags: ['storage', 'bathroom-supplies', 'follow-up'],
    },
    {
      questionCode: 'FUNCTIONALITY_19',
      category: 'Funkcjonalność i wyposażenie wnętrz',
      text: 'Ile godzin tygodniowo gotujecie?',
      type: 'slider',
      options: { min: 0, max: 20, step: 1, referencePoints: [{ value: 0, label: '0-5h' }, { value: 10, label: '5-15h' }, { value: 20, label: '>15h' }] },
      branchingLogic: { rules: [{ condition: { value: 10, operator: 'gt' }, action: 'JUMP', target: 'FUNCTIONALITY_19_FOLLOWUP' }] },
      relevantRooms: ["Kuchnia", "Jadalnia", "Spiżarnia", "Salon"],
      tags: ['cooking'],
    },
    {
      questionCode: 'FUNCTIONALITY_19_FOLLOWUP',
      category: 'Funkcjonalność i wyposażenie wnętrz',
      text: 'Dla ilu osób najczęściej gotujecie i czy potrzebujecie dużej spiżarni?',
      type: 'text',
      options: { placeholder: 'np. dla 4 osób, tak, potrzebujemy spiżarni' },
      relevantRooms: [],
      tags: ['cooking', 'follow-up'],
    },
    // === 2.3. Preferencje dotyczące utrzymania i konserwacji ===
    {
        questionCode: 'MAINTENANCE_1',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Ile godzin tygodniowo możecie poświęcić na sprzątanie?',
        type: 'slider',
        options: { min: 0, max: 7, step: 1, referencePoints: [{ value: 0, label: '0-2h' }, { value: 3, label: '2-5h' }, { value: 7, label: '>5h' }] },
        branchingLogic: { rules: [{ condition: { value: 2, operator: 'lt' }, action: 'JUMP', target: 'MAINTENANCE_1_FOLLOWUP' }] },
        relevantRooms: ["Pralnia", "Łazienka", "Kuchnia", "Salon", "Pokój dziecięcy"],
        tags: ['cleaning'],
    },
    {
        questionCode: 'MAINTENANCE_1_FOLLOWUP',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Jakie rozwiązania mogłyby pomóc zminimalizować czas sprzątania?',
        type: 'text',
        options: { placeholder: 'np. materiały odporne na plamy, gładkie powierzchnie' },
        relevantRooms: [],
        tags: ['cleaning', 'follow-up'],
    },
    {
        questionCode: 'MAINTENANCE_2',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Jak często musicie sprzątać po dzieciach lub zwierzętach?',
        type: 'single-choice',
        options: { choices: [{ value: 'daily', label: 'Codziennie' }, { value: 'weekly', label: 'Kilka razy w tygodniu' }, { value: 'rarely', label: 'Rzadko' }, { value: 'none', label: 'Nie dotyczy' }] },
        branchingLogic: { rules: [{ condition: { value: 'none', operator: 'neq' }, action: 'JUMP', target: 'MAINTENANCE_2_FOLLOWUP' }] },
        relevantRooms: ["Pokój dziecięcy", "Kącik dla zwierząt (np. dla psa/kota)", "Salon", "Kuchnia", "Łazienka"],
        tags: ['cleaning', 'children', 'pets'],
    },
    {
        questionCode: 'MAINTENANCE_2_FOLLOWUP',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'W jakich pomieszczeniach jest to największym wyzwaniem?',
        type: 'text',
        options: { placeholder: 'np. sierść w salonie, plamy w kuchni' },
        relevantRooms: [],
        tags: ['cleaning', 'children', 'pets', 'follow-up'],
    },
    {
        questionCode: 'MAINTENANCE_3',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Co jest ważniejsze: łatwe czyszczenie czy trwałość materiałów?',
        type: 'trade-off',
        options: {
            optionA: { value: 'easy_clean', label: 'Łatwe czyszczenie', description: 'Materiały mogą wymagać wymiany szybciej.' },
            optionB: { value: 'durable', label: 'Trwałość', description: 'Materiały mogą być trudniejsze w czyszczeniu.' }
        },
        relevantRooms: ["Kuchnia", "Łazienka", "Salon", "Pokój dziecięcy"],
        tags: ['cleaning', 'materials', 'trade-off'],
    },
    {
        questionCode: 'MAINTENANCE_4',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Wolisz materiały naturalne (więcej pielęgnacji) czy łatwe w utrzymaniu (np. syntetyczne)?',
        type: 'trade-off',
        options: {
            optionA: { value: 'natural', label: 'Naturalne', description: 'Wymagają więcej uwagi i pielęgnacji.' },
            optionB: { value: 'easy_care', label: 'Łatwe w utrzymaniu', description: 'Mogą być mniej "szlachetne".' }
        },
        relevantRooms: ["Salon", "Kuchnia", "Łazienka", "Jadalnia"],
        tags: ['materials', 'maintenance', 'trade-off'],
    },
    {
        questionCode: 'MAINTENANCE_5',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Czy ktoś z domowników ma alergie, które wpływają na wybór materiałów?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
        branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'MAINTENANCE_5_FOLLOWUP' }] },
        relevantRooms: ["Sypialnia", "Łazienka", "Kuchnia", "Salon"],
        tags: ['health', 'materials'],
    },
    {
        questionCode: 'MAINTENANCE_5_FOLLOWUP',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Jakie to alergie i dla ilu osób?',
        type: 'text',
        options: { placeholder: 'np. alergia na kurz, potrzebne materiały antypyłowe' },
        relevantRooms: [],
        tags: ['health', 'materials', 'follow-up'],
    },
    {
        questionCode: 'MAINTENANCE_6',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Wolisz styl minimalistyczny (mniej sprzątania) czy bogaty w dekoracje (więcej detali do czyszczenia)?',
        type: 'image-choice',
        options: { choices: [
            { value: 'minimalist', label: 'Minimalistyczny', imageUrl: '/images/placeholder.jpg' },
            { value: 'decorative', label: 'Dekoracyjny', imageUrl: '/images/placeholder.jpg' },
            { value: 'mixed', label: 'Mieszany', imageUrl: '/images/placeholder.jpg' }
        ]},
        relevantRooms: ["Salon", "Jadalnia", "Sypialnia"],
        tags: ['style', 'maintenance'],
    },
    {
        questionCode: 'MAINTENANCE_7',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Jak ważna jest dla Ciebie trwałość mebli i wykończeń (w skali od 1 do 5)?',
        type: 'slider',
        options: { min: 1, max: 5, referencePoints: [{ value: 1, label: 'OK na 2-3 lata' }, { value: 3, label: 'Oczekuję 5-7 lat' }, { value: 5, label: 'Chcę, by służyły >10 lat' }] },
        branchingLogic: { rules: [{ condition: { value: 2, operator: 'lt' }, action: 'JUMP', target: 'MAINTENANCE_7_FOLLOWUP' }] },
        relevantRooms: ["Pokój dziecięcy", "Kuchnia", "Salon", "Sypialnia"],
        tags: ['durability'],
    },
    {
        questionCode: 'MAINTENANCE_7_FOLLOWUP',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'W jakich sytuacjach jesteś w stanie zaakceptować mniejszą trwałość?',
        type: 'text',
        options: { placeholder: 'np. w pokoju dziecka, które szybko rośnie' },
        relevantRooms: [],
        tags: ['durability', 'follow-up'],
    },
    {
        questionCode: 'MAINTENANCE_8',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Czy korzystacie z usług profesjonalnego sprzątania?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
        branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'MAINTENANCE_8_FOLLOWUP' }] },
        relevantRooms: ["Kuchnia", "Łazienka", "Salon", "Pralnia"],
        tags: ['cleaning-services'],
    },
    {
        questionCode: 'MAINTENANCE_8_FOLLOWUP',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Jak często i w jakich pomieszczeniach?',
        type: 'text',
        options: { placeholder: 'np. co tydzień cały dom' },
        relevantRooms: [],
        tags: ['cleaning-services', 'follow-up'],
    },
    {
        questionCode: 'MAINTENANCE_9',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Czy poszukujecie rozwiązań łatwych w konserwacji (np. z wymiennymi elementami)?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
        branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'MAINTENANCE_9_FOLLOWUP' }] },
        relevantRooms: ["Pralnia", "Kuchnia", "Łazienka"],
        tags: ['maintenance', 'repair'],
    },
    {
        questionCode: 'MAINTENANCE_9_FOLLOWUP',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Jakie rozwiązania byłyby najbardziej pożądane?',
        type: 'text',
        options: { placeholder: 'np. wymienne fronty szafek, modułowe meble' },
        relevantRooms: [],
        tags: ['maintenance', 'repair', 'follow-up'],
    },
    {
        questionCode: 'MAINTENANCE_10',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Czy masz specjalne preferencje co do metod czyszczenia?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
        branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'MAINTENANCE_10_FOLLOWUP' }] },
        relevantRooms: ["Kuchnia", "Łazienka", "Salon"],
        tags: ['cleaning-methods'],
    },
    {
        questionCode: 'MAINTENANCE_10_FOLLOWUP',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Jakie to preferencje?',
        type: 'text',
        options: { placeholder: 'np. unikanie silnych detergentów, preferencja czyszczenia na mokro' },
        relevantRooms: [],
        tags: ['cleaning-methods', 'follow-up'],
    },
    {
        questionCode: 'MAINTENANCE_11',
        category: 'Preferencje dotyczące utrzymania i konserwacji',
        text: 'Wolisz materiały, które z czasem nabierają charakteru (np. patynują) czy takie, które wyglądają zawsze jak nowe?',
        type: 'image-choice',
        options: { choices: [
            { value: 'patina', label: 'Nabierające charakteru', imageUrl: '/images/placeholder.jpg' },
            { value: 'pristine', label: 'Zawsze jak nowe', imageUrl: '/images/placeholder.jpg' },
            { value: 'mixed', label: 'Mieszane', imageUrl: '/images/placeholder.jpg' }
        ]},
        relevantRooms: ["Salon", "Sypialnia", "Kuchnia"],
        tags: ['materials', 'aesthetics'],
    },
    // === 2.4. Preferencje oświetleniowe i klimatyczne ===
    {
        questionCode: 'LIGHTING_1',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'Ile godzin dziennie macie dostęp do naturalnego światła w kluczowych pomieszczeniach?',
        type: 'slider',
        options: { min: 0, max: 10, step: 1, referencePoints: [{ value: 0, label: '0-4h' }, { value: 5, label: '4-8h' }, { value: 10, label: '>8h' }] },
        branchingLogic: { rules: [{ condition: { value: 4, operator: 'lt' }, action: 'JUMP', target: 'LIGHTING_1_FOLLOWUP' }] },
        relevantRooms: ["Ogród zimowy", "Taras / Balkon / Loggia", "Salon", "Kuchnia", "Sypialnia", "Gabinet / Biuro domowe"],
        tags: ['lighting', 'natural-light'],
    },
    {
        questionCode: 'LIGHTING_1_FOLLOWUP',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'Jakie rozwiązania stosujecie, by adaptować się do małej ilości światła?',
        type: 'text',
        options: { placeholder: 'np. jasne kolory ścian, wiele punktów świetlnych' },
        relevantRooms: [],
        tags: ['lighting', 'natural-light', 'follow-up'],
    },
    {
        questionCode: 'LIGHTING_2',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'Jakiego rodzaju sztucznego oświetlenia potrzebujecie najczęściej?',
        type: 'multiple-choice',
        options: { choices: [
            { value: 'general', label: 'Ogólne, sufitowe' },
            { value: 'task', label: 'Punktowe, do pracy (np. nad blatem)' },
            { value: 'accent', label: 'Dekoracyjne, akcentujące' },
            { value: 'dimmable', label: 'Z możliwością ściemniania' },
            { value: 'automated', label: 'Automatyczne (np. z czujnikiem ruchu)' }
        ]},
        branchingLogic: { rules: [{ condition: { value: 'task', operator: 'contains' }, action: 'JUMP', target: 'LIGHTING_2_FOLLOWUP' }] },
        relevantRooms: ["Gabinet / Biuro domowe", "Kuchnia", "Sypialnia", "Łazienka", "Salon"],
        tags: ['lighting', 'artificial-light'],
    },
    {
        questionCode: 'LIGHTING_2_FOLLOWUP',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'Do jakich zadań najczęściej potrzebujecie oświetlenia punktowego?',
        type: 'text',
        options: { placeholder: 'np. do czytania, gotowania, makijażu' },
        relevantRooms: [],
        tags: ['lighting', 'artificial-light', 'follow-up'],
    },
    {
        questionCode: 'LIGHTING_3',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'Jaką barwę światła preferujecie w różnych sytuacjach?',
        type: 'image-choice',
        options: { choices: [
            { value: 'warm', label: 'Ciepła (do relaksu)', imageUrl: '/images/placeholder.jpg' },
            { value: 'neutral', label: 'Neutralna (do codziennych czynności)', imageUrl: '/images/placeholder.jpg' },
            { value: 'cold', label: 'Zimna (do pracy)', imageUrl: '/images/placeholder.jpg' }
        ]},
        relevantRooms: ["Sypialnia", "Gabinet / Biuro domowe", "Salon", "Kuchnia"],
        tags: ['lighting', 'light-temperature'],
    },
    {
        questionCode: 'LIGHTING_4',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'Czy macie miejsca wymagające specjalistycznego oświetlenia?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
        branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'LIGHTING_4_FOLLOWUP' }] },
        relevantRooms: ["Gabinet / Biuro domowe", "Kuchnia", "Pokój hobby / Pracownia", "Łazienka", "Garderoba"],
        tags: ['lighting', 'specialty-lighting'],
    },
    {
        questionCode: 'LIGHTING_4_FOLLOWUP',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'Jakie to miejsca i jakie oświetlenie jest tam potrzebne?',
        type: 'text',
        options: { placeholder: 'np. oświetlenie lustra w łazience, stołu w pracowni' },
        relevantRooms: [],
        tags: ['lighting', 'specialty-lighting', 'follow-up'],
    },
    {
        questionCode: 'LIGHTING_5',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'Jak ważna jest dla Was możliwość regulacji natężenia światła (ściemnianie)?',
        type: 'slider',
        options: { min: 1, max: 5, referencePoints: [{ value: 1, label: 'Nieważna' }, { value: 3, label: 'Przydatna' }, { value: 5, label: 'Kluczowa' }] },
        branchingLogic: { rules: [{ condition: { value: 3, operator: 'gt' }, action: 'JUMP', target: 'LIGHTING_5_FOLLOWUP' }] },
        relevantRooms: ["Salon", "Sypialnia", "Gabinet / Biuro domowe", "Kuchnia", "Jadalnia"],
        tags: ['lighting', 'dimming'],
    },
    {
        questionCode: 'LIGHTING_5_FOLLOWUP',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'W jakich pomieszczeniach i sytuacjach regulacja światła jest najważniejsza?',
        type: 'text',
        options: { placeholder: 'np. w salonie podczas oglądania filmów' },
        relevantRooms: [],
        tags: ['lighting', 'dimming', 'follow-up'],
    },
    {
        questionCode: 'CLIMATE_1',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'Czy macie problemy z wentylacją lub wilgotnością w domu?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
        branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'CLIMATE_1_FOLLOWUP' }] },
        relevantRooms: ["Łazienka", "Pralnia", "Kuchnia", "Ogród zimowy", "Sypialnia", "Piwnica"],
        tags: ['climate', 'ventilation'],
    },
    {
        questionCode: 'CLIMATE_1_FOLLOWUP',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'Na czym polega problem i w jakich pomieszczeniach występuje?',
        type: 'text',
        options: { placeholder: 'np. wilgoć i pleśń w łazience' },
        relevantRooms: [],
        tags: ['climate', 'ventilation', 'follow-up'],
    },
    {
        questionCode: 'CLIMATE_2',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'Czy planujecie instalację lub korzystacie z klimatyzacji?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
        branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'CLIMATE_2_FOLLOWUP' }] },
        relevantRooms: ["Sypialnia", "Pokój fitness / Siłownia domowa", "Gabinet / Biuro domowe", "Salon"],
        tags: ['climate', 'ac'],
    },
    {
        questionCode: 'CLIMATE_2_FOLLOWUP',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'W ilu pomieszczeniach i w jakich sytuacjach klimatyzacja jest najważniejsza?',
        type: 'text',
        options: { placeholder: 'np. w sypialni podczas upałów' },
        relevantRooms: [],
        tags: ['climate', 'ac', 'follow-up'],
    },
    {
        questionCode: 'CLIMATE_3',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'Jak ważna jest dla Was stała temperatura w pomieszczeniach?',
        type: 'slider',
        options: { min: 1, max: 5, referencePoints: [{ value: 1, label: 'Nieważna' }, { value: 3, label: 'Ważna' }, { value: 5, label: 'Kluczowa' }] },
        branchingLogic: { rules: [{ condition: { value: 3, operator: 'gt' }, action: 'JUMP', target: 'CLIMATE_3_FOLLOWUP' }] },
        relevantRooms: ["Sypialnia", "Kuchnia", "Gabinet / Biuro domowe", "Pokój dla seniora"],
        tags: ['climate', 'temperature-stability'],
    },
    {
        questionCode: 'CLIMATE_3_FOLLOWUP',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'W jakich pomieszczeniach utrzymanie stałej temperatury jest priorytetem?',
        type: 'text',
        options: { placeholder: 'np. w sypialni dziecka, w gabinecie' },
        relevantRooms: [],
        tags: ['climate', 'temperature-stability', 'follow-up'],
    },
    {
      questionCode: 'CLIMATE_4',
      category: 'Preferencje oświetleniowe i klimatyczne',
      text: 'Czy domownicy mają różne preferencje co do temperatury?',
      type: 'single-choice',
      options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
      branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'CLIMATE_4_FOLLOWUP' }] },
      relevantRooms: ["Sypialnia", "Kuchnia", "Pokój dla seniora", "Salon"],
      tags: ['climate', 'preferences'],
    },
    {
      questionCode: 'CLIMATE_4_FOLLOWUP',
      category: 'Preferencje oświetleniowe i klimatyczne',
      text: 'Jakie rozwiązania mogłyby pomóc pogodzić te różnice?',
      type: 'text',
      options: { placeholder: 'np. indywidualne sterowanie ogrzewaniem w pokojach' },
      relevantRooms: [],
      tags: ['climate', 'preferences', 'follow-up'],
    },
    {
        questionCode: 'CLIMATE_5',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'Czy potrzebujecie indywidualnego sterowania temperaturą w poszczególnych pokojach?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak, to kluczowe' }, { value: 'nice_to_have', label: 'Byłoby miło' }, { value: 'no', label: 'Nie, nie jest to konieczne' }] },
        relevantRooms: ["Gabinet / Biuro domowe", "Sypialnia", "Pokój dla seniora", "Pokój młodzieżowy"],
        tags: ['climate', 'hvac-control'],
    },
    {
        questionCode: 'CLIMATE_6',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'Czy ktoś z domowników ma alergie wpływające na potrzeby wentylacyjne (np. na pyłki)?',
        type: 'single-choice',
        options: { choices: [{ value: 'yes', label: 'Tak' }, { value: 'no', label: 'Nie' }] },
        branchingLogic: { rules: [{ condition: { value: 'yes', operator: 'eq' }, action: 'JUMP', target: 'CLIMATE_6_FOLLOWUP' }] },
        relevantRooms: ["Sypialnia", "Łazienka", "Kuchnia", "Salon"],
        tags: ['climate', 'health', 'ventilation'],
    },
    {
        questionCode: 'CLIMATE_6_FOLLOWUP',
        category: 'Preferencje oświetleniowe i klimatyczne',
        text: 'Jakie to alergie i jakie rozwiązania wentylacyjne byłyby pomocne?',
        type: 'text',
        options: { placeholder: 'np. alergia na pyłki, potrzebne filtry w wentylacji' },
        relevantRooms: [],
        tags: ['climate', 'health', 'ventilation', 'follow-up'],
    }
  ];

  for (const q of functionalQuestions) {
    await prisma.question.create({
      data: {
        ...q,
        quizId: functionalQuiz.id,
      },
    });
  }

  console.log(`✅ Dodano ${functionalQuestions.length} pytań do Quizu Funkcjonalnego.`);

  console.log('\n🎉 Seedowanie zakończone pomyślnie!');
}

main()
  .catch((e) => {
    console.error('❌ Błąd podczas seedowania:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
