export const styleClusters = [
  ["Japandi", "Scandinavian", "Zen", "Biophilic"],
  ["Minimalist", "Simple", "Contemporary"],
  ["Modern", "Luxury", "Neoclassic"],
  ["Industrial", "Loft", "Retro futuristic"],
  ["Glamour", "Hollywood glam", "Art deco"],
  ["Boho", "Boho-chic", "Modern boho", "Eclectic"],
  ["Farmhouse", "Cottagecore", "French country", "Rustic"],
  ["Midcentury modern", "Vintage", "Retro"],
  ["Parisian", "French", "Mediterranean"],
  ["Traditional", "Baroque", "Art nouveau"],
  ["Shabby chic", "Coastal", "Nautical"],
  ["Futuristic", "Cyberpunk", "Vaporwave"],
  ["Tropical", "Tribal"],
  ["Japanese design", "Wabi-sabi"],
  ["Maximalist", "Pop-art"],
  ["Eco-friendly", "Urban jungle"],
  ["Gaming room", "Medieval", "Gothic"],
  ["Seasonal & Special", "Hot pink", "Easter", "Christmas", "Halloween", "Chinese New Year", "Ski chalet", "Airbnb", "Sketch"],
];
